[book]
authors = ["ashutosh jain"]
language = "en"
multilingual = false
src = "src"
title = "Arjun Uvaach"
description = "discovering Gita and Maha-bharata"

[output.html]
theme = "src/theme"
git-repository-url = "https://github.com/ashutoshmjain/gita"
cname = "gita.shutri.com"
no-section-label = true
curly-quotes = true

[output.html.print]
enable = false    # include support for printable output


