[book]
authors = ["ashutosh jain"]
language = "en"
multilingual = false
src = "src"
title = "arjunUvaach"

[output.html]
google-analytics = "G-LMQ4L2V1QD"
default-theme = "ayu"
git-repository-url = "https://github.com/ashutoshmjain/gita"
