[book]
authors = ["ashutosh jain"]
language = "en"
multilingual = false
src = "src"
title = "arjun uvaach"
description = "discovering Gita and Maha-bharata"

[output.html]
theme = "src/theme"
cname = "gita.shutri.com"
no-section-label = true

[output.html.print]
enable = false    # include support for printable output
page-break = true # insert page-break after each chapter
