[book]
authors = ["ashutosh jain"]
language = "en"
multilingual = false
src = "src"
title = "arjunUvaach"

[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/ashutoshmjain/gita"
cname = "gita.shutri.com"
edit-url-template = "https://github.com/ashutoshmjain/gita/edit/main/{path}"
no-section-label = true
